// frontend/src/components/AlbumGrid.tsx
import type { AlbumT, SizeData, OverlayT } from "../types";

import Album from "./Album";
import Overlay from "./Overlay";
import { padding } from "../constants";

function getArtUrl(album: AlbumT, sizeData: SizeData): string {
  const useBigArt = true;
  if (useBigArt || sizeData.cellSize > 300) {
    return album.images[0].url;
  } else if (sizeData.cellSize > 64) {
    return album.images[1].url;
  } else {
    return album.images[0].url;
  }
}

function calculateOverlay(
  gridIndex: number,
  sizeData: SizeData,
  album: AlbumT
): OverlayT {
  const colPosition = gridIndex % sizeData.nGridCols;
  const rowPosition = Math.floor(gridIndex / sizeData.nGridCols);
  const leftHalf = colPosition < Math.floor(sizeData.nGridCols / 2);
  const topHalf = rowPosition < Math.floor(sizeData.nRows / 2);

  const overlayColumn = leftHalf
    ? colPosition + 2
    : colPosition + 1 - sizeData.overlayMultiplier;
  const overlayRow = topHalf
    ? rowPosition + 1
    : rowPosition + 2 - sizeData.overlayMultiplier;

  const artUrl = getArtUrl(album, sizeData);
  const overlay: OverlayT = {
    overlayColumn,
    overlayRow,
    album,
    artUrl,
  };
  return overlay;
}

export default function Main({
  albums,
  extraAlbums,
  allAlbumIds,
  setSelectedAlbum,
  overlay,
  setOverlay,
  overlayIsContext,
  setOverlayIsContext,
  searchQuery,
  clearSearchQuery,
  refreshAlbums,
  sizeData,
}: {
  albums: AlbumT[];
  extraAlbums: AlbumT[];
  allAlbumIds: Set<string>;
  setSelectedAlbum: (album: AlbumT | null) => void;
  overlay: OverlayT | null;
  setOverlay: (overlay: OverlayT | null) => void;
  overlayIsContext: boolean;
  setOverlayIsContext: (_: boolean) => void;
  searchQuery: string;
  clearSearchQuery: () => void;
  refreshAlbums: () => Promise<void>;
  sizeData: SizeData;
}) {
  const nExtraAlbums = sizeData.nRows * sizeData.nGridCols - albums.length;
  const albumsWithExtra = albums.concat(extraAlbums.slice(0, nExtraAlbums));

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: `repeat(${sizeData.nGridCols}, ${sizeData.cellSize}px)`,
        gridTemplateRows: `repeat(${sizeData.nRows}, ${sizeData.cellSize}px)`,
        position: "relative",
      }}
    >
      {albumsWithExtra.map((album, i) => (
        <div>
          <Album
            album={album}
            setSelectedAlbum={setSelectedAlbum}
            searchQuery={searchQuery}
            clearSearchQuery={clearSearchQuery}
            overlayData={calculateOverlay(i, sizeData, album)}
            overlayIsContext={overlayIsContext}
            setOverlayIsContext={setOverlayIsContext}
            setOverlay={setOverlay}
            sizeData={sizeData}
          />
        </div>
      ))}
      {overlay && (
        <Overlay
          overlay={overlay}
          overlayIsContext={overlayIsContext}
          setOverlayIsContext={setOverlayIsContext}
          setOverlay={setOverlay}
          allAlbumIds={allAlbumIds}
          refreshAlbums={refreshAlbums}
          sizeData={sizeData}
        />
      )}
    </div>
  );
}

// frontend/src/components/AlbumGrid.vue
<template>
  <div class="container">
    <div class="album-grid">
      <img v-if="overlayAlbum" class="album-overlay" :src="overlayAlbum.data.images[0].url"
        :alt="overlayAlbum.data.name" :width="overlaySize" :height="overlaySize" />
    </div>
    <div class="album-grid">
      <Album v-for="(album, i) in albumsWithExtra" :key="`${i}-${album.id}`" :album="album" :cellSize="cellSize"
        :padding="padding" :overlayMultiplier=overlayMultiplier :nCols=nCols :nRows=nRows :index=i :nColsAll=nColsAll
        :isInLibrary=true v-on:play="propagatePlay($event)" v-on:hover="hover($event)" v-on:clearHover="clearHover"
        v-on:refreshAlbums="propagateRefreshAlbums" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type { Ref } from 'vue';

import Album from "./Album.vue";
import type { AlbumT, OverlayT } from '../types.js'


const props = defineProps<{
  albums: AlbumT[]
  extraAlbums: AlbumT[]
  cellSize: number
  overlayMultiplier: number
  padding: number
  nRows: number
  nCols: number
  nColsAll: number
}>()

const emit = defineEmits<{
  (e: "play", arg: AlbumT): void
  (e: "refreshAlbums", arg: (() => void)): void
}>()

const overlayAlbum: Ref<OverlayT | null> = ref(null);

const cellSizeStr = computed(() => `${props.cellSize}px`)
const overlaySize = computed(() => props.cellSize * props.overlayMultiplier - props.padding * 2)
const overlayColumn = computed(() => {
  if (!overlayAlbum.value) {
    return 1
  } else if (overlayAlbum.value.leftHalf) {
    return overlayAlbum.value.colPosition + 2
  } else {
    return overlayAlbum.value.colPosition + 1 - props.overlayMultiplier
  }
})
const overlayRow = computed(() => {
  if (!overlayAlbum.value) {
    return 1
  } else if (overlayAlbum.value.topHalf) {
    return overlayAlbum.value.rowPosition + 1
  } else {
    return overlayAlbum.value.rowPosition + 2 - props.overlayMultiplier
  }
})

const nExtraAlbums = computed(() => (props.nRows * props.nCols) - props.albums.length)
const albumsWithExtra = computed(() => props.albums.concat(props.extraAlbums.slice(0, nExtraAlbums.value)))


function propagatePlay(arg: AlbumT) {
  emit("play", arg);
}

function hover(arg: OverlayT) {
  overlayAlbum.value = arg
}

function clearHover() {
  overlayAlbum.value = null
}

function propagateRefreshAlbums(cb: (() => void)) {
  emit("refreshAlbums", cb);
}

</script>


<style scoped>
.container {
  position: relative;
}

.album-grid {
  display: grid;
  grid-template-columns: repeat(v-bind(nCols), v-bind(cellSizeStr));
  grid-template-rows: repeat(v-bind(nRows), v-bind(cellSizeStr));
  position: absolute;
}

.album-overlay {
  grid-row-start: v-bind(overlayRow);
  grid-column-start: v-bind(overlayColumn);
  padding: 2px;
  z-index: 1
}
</style>
